### ISSUE TITLE
Can't import flow

### ISSUE THREAD

**Issue by itsmylife44** [adonisd/miner#1]
Hello , i try to import the flow on node-Red but it's noot working .  
![awdawdwad](https://user-images.githubusercontent.com/34112129/36568515-9b2f5ce8-182a-11e8-9c17-996177cec503.PNG)

**Comment by adonisd** [comment]
Hey,
Sorry it took long to reply. I actually made a lot of changes since I created this page. I put the flow to copy in page/flow.txt can you try that ?
